## The N-Body Problem
This is a classic problem that's been of interest since the time of Newton. As it relates to the positions in of heavenly bodies, it was at the center of great debates that took place during the 1500s and involved such greats as Tycho Brahe (my favorite), Nicolaus Copernicus, Galileo, and Kepler.

We'll attack the problem with a brute force approach, adding up all the forces occurring between bodies. However, many good alternatives exist, and will be the topic of at least one graduate project.

### Two bodies
Consider a force such as gravity, which pulls the moon toward the Earth *and the Earth toward the moon*. Generalize these two bodies to a pair of particles.

Suppose the particles are numbered 1 and 2. The force on 1 due to 2 will be labeled $\mathbf{F}_{12}$. Note it is a vector quantity. What about the force on 2 due to 1? Well, it's going to be anti-symmetric in the cases we will consider, $\mathbf{F}_{12} = -\mathbf{F}_{21}$. What might this force look like? It will be a *central force*, expressed as

$$\mathbf{F}_{12}(\mathbf{r}) = |F_{12}(r)|\mathbf{\hat r}_{12}.$$

This is like what we've seen before where the magnitude is abstracted as $ |\mathbf{F}_{12}(\mathbf{r})|$, and we focus on the direction in $\mathbf{\hat{r}}_{12}$. 

This direction is given by
$$\mathbf{\hat{r}}_{12} = \frac{\mathbf{r}_1 - \mathbf{r}_2}{|\mathbf{r}_1 - \mathbf{r}_2|},$$
which points from 2 to 1.

![The difference in vectors.](vector_diff.png)

So, now we know the direction of this abstract force. How do we account for its working in both directions? That is particle 1 on 2 and 2 on 1.

It is convenient to write the forces in a matrix, where the matrix entry $\mathcal{F}_{ij}$ is the force of $j$ on $i$. There is no self-interaction; $\mathcal{F}_{ii}$=0.

$$\mathcal{F} =
\begin{bmatrix}
0 & \mathbf{F}_{12}  \\
\mathbf{F}_{21}&0\\
\end{bmatrix}
=
\begin{bmatrix}
0 & \mathbf{F}_{12}  \\
-\mathbf{F}_{12}&0\\
\end{bmatrix}$$

Such a matrix has two important properties; 
* the sum of each row is the total force on particle $i$ - $\mathbf{F}_i = \sum_j \mathcal{F}_{ij}$
* the matrix is anti-symmetric, so only the upper triangle needs to be computed.

But, what about those entries in that matrix - it looks like **they should be vectors**. In practice, it will be useful to maintain a scalar matrix for each dimension, a matrix of the $x$ components of force, $\mathcal{F}^x_{ij}$, and $y$ components, $\mathcal{F}^y_{ij}$, etc. 

### Three and more bodies
It probably occurred to you that the matrices are a lot of work when the forces are just $\mathbf{F}_{12}$ and $-\mathbf{F}_{12}$; the result of a single calculation. But, watch what happens with three bodies.

![The positions of and vectors between three bodies.](3body.png)

$$\mathcal{F} =
\begin{bmatrix}
0 & \mathbf{F}_{12} & \mathbf{F}_{13} \\
\mathbf{F}_{21} & 0 & \mathbf{F}_{23}\\
\mathbf{F}_{31}  & \mathbf{F}_{32} & 0
\end{bmatrix}$$

In this case, the sums of the rows are critical because because each body is attracted to 2 other bodies. But the formalism is powerful and appropriate. How many unique calculations need to be done? 

$$\mathcal{F} =
\begin{bmatrix}
0 & \mathbf{F}_{12} & \mathbf{F}_{13} \\
-\mathbf{F}_{12} & 0 & \mathbf{F}_{23}\\
-\mathbf{F}_{13}  & -\mathbf{F}_{23} & 0
\end{bmatrix}$$

Just 3, the upper triangle of the matrix. The most important aspect is, again, the fact that the total force on each particle is computed by summing its row:

$$\mathbf{F}_i = \sum_j \mathcal{F}_{ij}$$

With this statement, I think we see the sketch of the n-body algorithm. First we fill in a matrix:

`for i in range(len(particles):
    for j range(i+1,len(particles)):
        rij = particles.r(i) - particles.r(j)
        Fmatrix[i,j] = f(rij) * rij / norm(rij)
`

Then we find the force on each particle with sums over the rows of `FMatrix`

The generalization from three bodies to n-bodies is superficial.

There are opportunities to vectorize the operations by using `repmat` to create highly redundant arrays of coordinate data. Doing this may interest you, but it isn't necessary. It does tend to obfuscate code. I do wonder, but haven't tried to see if `numba` doesn't get the speedups sought.

### The force
It has been worthwhile to abstract the force. As you can see in the psuedo-code/Python above, a function handle is a nice mechanism for this. However, we'll be concerned with gravitational forces in this class. That force is

$$\mathbf{F}_{12} = -G \frac{m_1m_2}{r_{12}^2}\mathbf{\hat{r}}_{12}$$

Which can more conveniently be written

$$\mathbf{F}_{12} = -G \frac{m_1m_2}{r_{12}^3}\mathbf{r}_{12}$$

If you are curious about why we generalize, let me provide at least one example. There is a rich literature in molecular dynamics which involves the use of Lennard-Jones type potentials

$$4\epsilon \left[\left(\frac{\sigma}{r}\right)^{12}-\left(\frac{\sigma}{r}\right)^{6}\right]$$

Which describe weak attraction/strong repulsion. Forces are found by differentiation of the potential.

Of late, this concept has been extended to something called *discrete-element modeling*, which is good for large assemblages of granular material.

### Objective

Write an ODE function that provides the derivatives for the n-body problem. Assume as you have in the past that the state is entering as some vector `y` and the function will return `dydt`, or $\frac{dy}{dt}$. To match signatures, the function will have to accept a `t` or time that is not used, and a `p` which is a parameter. Here, it suggest `p` be made a dictionary of parameters.

The difficulties to be resolved in implementation include

* accounting for the masses of the particles.
* accounting for the dimension of the problem.
* accounting for the half way point, or where the position information stops, and the velocity information begins.
* not computing the same thing twice; only find $\mathbf{F}_{ij}$, not $\mathbf{F}_{ji}$. But, account for both.
* summing the columns so that each row's sum is the force on a particle.
* determining the acceleration and not the mass.
* handling a parameter called `fix_first` that prevents the first particle from moving. This is useful for simulating massive objects like the sun, and will help with a simulation of the helium atom.

Below, you will find the signature for the function, and some test data results to determine if the function is working correctly. Finish the function and verify the test data is giving the correct outputs.

In [61]:
import numpy as np

def n_body(t,x,p):
    """
    ODE function for the n-body problem.

    Parameters:
    t (float): time (unused but required for ODE solver compatibility)
    x (np.array): state vector containing positions and velocities
    p (dict): parameters dictionary containing:
        - m (list): masses of particles
        - G (float): gravitational constant
        - dimension (int): number of spatial dimensions
        - fix_first (bool): whether to fix the first particle in place

    Returns:
    np.array: derivative of state vector (velocities and accelerations)
    """
    # Extract parameters
    masses = np.array(p['m'])
    G = p['G']
    dimensions = p['dimension']
    n_bodies = len(masses)

    # Initialize derivative vector
    dxdt = np.zeros_like(x)

    # First half of dxdt is just the velocities from second half of x
    dxdt[:n_bodies*dimensions] = x[n_bodies*dimensions:]  # n_bodies = 3, dimensions = 2; dxdt[0:6] = x[6:12]

    # Initialize force matrices for each dimension
    force_matrices = np.zeros((dimensions, n_bodies, n_bodies))

    # Calculate forces between all pairs of bodies
    for i in range(n_bodies):
        for j in range(i+1, n_bodies):  # Only upper triangle

            # Calculate displacement vector between bodies i and j
            r_ij = []  # x, y
            for d in range(dimensions):
                displacement = x[i*dimensions + d] - x[j*dimensions + d]
                print(f"Displacement between body {i} and body {j} in dimension {d}: {displacement}")
                r_ij.append(displacement)

            r_ij = np.array(r_ij)  # x, y displacement

            # Calculate distance
            r = np.sqrt(np.sum(r_ij**2))
            print(f"Distance between body {i} and body {j}: {r}")

            # Calculate gravitational force magnitude
            force_mag = -G * masses[i] * masses[j] / (r**3)
            print(f"Force magnitude between body {i} and body {j}: {force_mag}")

            # Calculate force components and fill force matrices
            for d in range(dimensions):
                force_matrices[d][i,j] = force_mag * r_ij[d]
                force_matrices[d][j,i] = -force_matrices[d][i,j]  # Fill in lower triangle

    print("Force matrix x:")
    print(force_matrices[0])
    print("Force matrix y:")
    print(force_matrices[1])

    # Sum forces on each body and calculate accelerations
    for i in range(n_bodies):
        if p.get('fix_first', False) and i == 0:
            # If fix_first is True, first body doesn't move
            continue

        # Calculate acceleration components for each dimension
        for d in range(dimensions):
            print(force_matrices[d][i])
            total_force = np.sum(force_matrices[d][i])
            dxdt[n_bodies*dimensions + i*dimensions + d] = total_force / masses[i]  # vx1, vy1, vx2, vy2, vx3, vy3, [ax1, ay1,] ax2, ay2, ax3, ay3

    return dxdt

In [62]:
"""
Test data - make sure that your function reproduces the following.
Why not add a row of differences and make sure they are zero?
"""

# Order is all positions then all velocities grouped by body.
# eg, three bodies in two dimensions:
# x1,y1,x2,y2,x3,y3,vx1,vy1,vx2,vy2,vx3,vy3

from prettytable import PrettyTable

euler      = np.array([0,0,1,0,-1,0,0,0,0,.8,0,-.8])
four_body  = np.array([1.382857,0,\
                   0,0.157030,\
                  -1.382857,0,\
                   0,-0.157030,\
                   0,0.584873,\
                   1.871935,0,\
                   0,-0.584873,\
                  -1.871935,0])
helium_1 = np.array([0,0,2,0,-1,0,0,0,0,.95,0,-1])

# The data structure holding parameters. You need not
# do it this way, but it's nice.

p = {'m': [1,1,1], 'G': 1, 'dimension': 2, 'fix_first': False}
p4 = {'m': [1,1,1,1], 'G': 1, 'dimension': 2, 'fix_first': False}
phe = {'m': [2,-1,-1], 'G': 1, 'dimension': 2, 'fix_first': True}

headings = ['RUN','x1','y1','x2','y2','x3','y3','vx1','vy1','vx2','vy2','vx3','vy3']
t = PrettyTable(headings)
t.add_row(['euler'] + list(n_body(0, euler, p)))
t.add_row(['He'] + list(n_body(0, helium_1, phe)))
print(t)

headings = ['RUN','x1','y1','x2','y2','x3','y3','x4','y4','vx1','vy1','vx2','vy2','vx3','vy3','vx4','vy4']
t = PrettyTable(headings)
t.add_row(['4 body'] + list(n_body(0, four_body, p4)))
print(t)

Displacement between body 0 and body 1 in dimension 0: -1.0
Displacement between body 0 and body 1 in dimension 1: 0.0
Distance between body 0 and body 1: 1.0
Force magnitude between body 0 and body 1: -1.0
Displacement between body 0 and body 2 in dimension 0: 1.0
Displacement between body 0 and body 2 in dimension 1: 0.0
Distance between body 0 and body 2: 1.0
Force magnitude between body 0 and body 2: -1.0
Displacement between body 1 and body 2 in dimension 0: 2.0
Displacement between body 1 and body 2 in dimension 1: 0.0
Distance between body 1 and body 2: 2.0
Force magnitude between body 1 and body 2: -0.125
Force matrix x:
[[ 0.    1.   -1.  ]
 [-1.    0.   -0.25]
 [ 1.    0.25  0.  ]]
Force matrix y:
[[ 0. -0. -0.]
 [ 0.  0. -0.]
 [ 0.  0.  0.]]
[ 0.  1. -1.]
[ 0. -0. -0.]
[-1.    0.   -0.25]
[ 0.  0. -0.]
[1.   0.25 0.  ]
[0. 0. 0.]
Displacement between body 0 and body 1 in dimension 0: -2.0
Displacement between body 0 and body 1 in dimension 1: 0.0
Distance between body 0 and 

In [63]:
expected_euler = np.array([0.0, 0.0, 0.0, 0.8, 0.0, -0.8, 0.0, 0.0, -1.25, 0.0, 1.25, 0.0])
expected_helium = np.array([0.0, 0.0, 0.0, 0.95, 0.0, -1.0, 0.0, 0.0, -0.3888888888888889, -0.0, 1.8888888888888888, -0.0])
expected_4body = np.array([0.0, 0.584873, 1.871935, 0.0, 0.0, -0.584873, -1.871935, 0.0, -1.1566897259697542, 0.0, 0.0, -10.255026586107203, 1.1566897259697542, 0.0, 0.0, 10.255026586107205])

calculated_euler = n_body(0, euler, p)
calculated_helium = n_body(0, helium_1, phe)
calculated_4body = n_body(0, four_body, p4)

print("Difference between expected and calculated values for Euler:")
headings = ['RUN','x1','y1','x2','y2','x3','y3','vx1','vy1','vx2','vy2','vx3','vy3']
t = PrettyTable(headings)
t.add_row(['calculated_euler'] + list(calculated_euler))
t.add_row(['expected_euler'] + list(expected_euler))
t.add_divider()
t.add_row(['difference'] + list(expected_euler - calculated_euler))
print(t)

print("Difference between expected and calculated values for Helium:")
headings = ['RUN','x1','y1','x2','y2','x3','y3','vx1','vy1','vx2','vy2','vx3','vy3']
t = PrettyTable(headings)
t.add_row(['calculated_helium'] + list(calculated_helium))
t.add_row(['expected_helium'] + list(expected_helium))
t.add_divider()
t.add_row(['difference'] + list(expected_helium - calculated_helium))
print(t)

print("Difference between expected and calculated values for 4-body:")
headings = ['RUN','x1','y1','x2','y2','x3','y3','x4','y4','vx1','vy1','vx2','vy2','vx3','vy3','vx4','vy4']
t = PrettyTable(headings)
t.add_row(['calculated_4body'] + list(calculated_4body))
t.add_row(['expected_4body'] + list(expected_4body))
t.add_divider()
t.add_row(['difference'] + list(expected_4body - calculated_4body))
print(t)


Displacement between body 0 and body 1 in dimension 0: -1.0
Displacement between body 0 and body 1 in dimension 1: 0.0
Distance between body 0 and body 1: 1.0
Force magnitude between body 0 and body 1: -1.0
Displacement between body 0 and body 2 in dimension 0: 1.0
Displacement between body 0 and body 2 in dimension 1: 0.0
Distance between body 0 and body 2: 1.0
Force magnitude between body 0 and body 2: -1.0
Displacement between body 1 and body 2 in dimension 0: 2.0
Displacement between body 1 and body 2 in dimension 1: 0.0
Distance between body 1 and body 2: 2.0
Force magnitude between body 1 and body 2: -0.125
Force matrix x:
[[ 0.    1.   -1.  ]
 [-1.    0.   -0.25]
 [ 1.    0.25  0.  ]]
Force matrix y:
[[ 0. -0. -0.]
 [ 0.  0. -0.]
 [ 0.  0.  0.]]
[ 0.  1. -1.]
[ 0. -0. -0.]
[-1.    0.   -0.25]
[ 0.  0. -0.]
[1.   0.25 0.  ]
[0. 0. 0.]
Displacement between body 0 and body 1 in dimension 0: -2.0
Displacement between body 0 and body 1 in dimension 1: 0.0
Distance between body 0 and 